@echo off
echo Compiling resource file...
windres info.rc -O coff -o bin\info.res
echo Resource file compiled. Compiling executable...
g++ main.cpp bin\info.res -o bin\main.exe
echo Compilation complete. Compressing with UPX for size optimization...
upx bin\main.exe
pause